spring:
  application:
    name: ClientService
  main:
    banner-mode: 'off'

server:
  port: 8801

spring.datasource:
  url: jdbc:h2:file:~/ClientService;DB_CLOSE_ON_EXIT=FALSE
  driverClassName: org.h2.Driver
  username: sa
  password:

spring.jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  hibernate.ddl-auto: create-drop
  generate-ddl: true
  properties.hibernate.hbm2ddl.auto: create-drop