spring:
  application:
    name: Eureka
  main:
    banner-mode: 'off'

server:
  port: 8761
#  port: 8762

eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://{eureka.instance.hostname}:8762/eureka
#    serviceUrl:
#      defaultZone: http://{eureka.instance.hostname}:8761/eureka

