spring:
  application:
    name: Eureka
  main:
    banner-mode: 'off'

server:
  port: 8762

eureka:
  server:
    enable-self-preservation: false
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

